<?php


namespace Tests\Controllers;


use App\Models\BrazilStates;
use CoffeeCode\DataLayer\Connect;

class BrazilStatesTest extends \PHPUnit\Framework\TestCase
{
    protected function setUp(): void
    {
        Connect::getInstance()->beginTransaction();
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    protected function tearDown(): void
    {
        Connect::getInstance()->rollBack();
        parent::tearDown(); // TODO: Change the autogenerated stub
    }

    public function testCreateIndexWithDatabaseEmpty()
    {
        $rsponseFake = (new BrazilStates());
        $classFake = $this->createMock(BrazilStates::class);
        $classFake->method('find')->willReturn($rsponseFake);

        $response = (new \App\Controllers\BrazilStates())->index();

        $this->assertFalse($response);
    }
}