<?php


namespace Tests\Controllers;


use App\Models\Category;
use App\Models\Product;
use CoffeeCode\DataLayer\Connect;
use CoffeeCode\DataLayer\DataLayer;

class IntegrationTest extends \PHPUnit\Framework\TestCase
{
//    private $objectProduct;
//    private $objectCategory;
//
////    protected function setUp(): void
////    {
////        $this->objectCategory = (new \App\Controllers\Category());
////        $this->objectProduct = (new \App\Controllers\Product());
////
////        parent::setUp(); // TODO: Change the autogenerated stub
////    }
////
////    protected function tearDown(): void
////    {
////        unset($this->objectCategory);
////        unset($this->objectProduct);
////
////
////        parent::tearDown(); // TODO: Change the autogenerated stub
////    }
//
//    public function dataProvider(): array
//    {
//        return [
//            [
//                (new \App\Controllers\Product())->create([
//                    'name' => 'sabão em pó',
//                    'category_id' => 99999,
//                    'price' => 6.90,
//                    'quantity' => 5
//                ])
//            ],
//            [
//                (new \App\Controllers\Product())->create([
//                    'name' => 'desinfetante',
//                    'price' => 2.50,
//                    'quantity' => 12
//                ])
//            ],
//            [
//                (new \App\Controllers\Product())->create([
//                    'name' => 'desinfetante'
//                ])
//            ],
//            [
//                (new \App\Controllers\Product())->create([
//                    'quantity' => 5
//                ])
//            ],
//            [
//                (new \App\Controllers\Product())->create([
//                    'price' => 6.90,
//                ])
//            ],
//            [
//                (new \App\Controllers\Product())->create([
//                    'category_id' => 99999,
//                    'quantity' => 5
//                ])
//            ],
//            [
//                (new \App\Controllers\Product())->create([
//                    'name' => 'sabão em pó',
//                    'category_id' => 99999,
//                    'price' => 6.90,
//                ])
//            ],
//            [
//                (new \App\Controllers\Product())->create([
//                    'category_id' => 99999,
//                    'quantity' => 5
//                ])
//            ],
//            [
//                (new \App\Controllers\Product())->create([])
//            ],
//        ];
//    }
//
//    /**
//     * @dataProvider dataProvider
//     */
//    public function testForCreateProductWithFieldRequiredEmpty($response)
//    {
//        $this->assertFalse($response);
//    }

    public function testError()
    {
//        $this->objectCategory = (new \App\Controllers\Category())->create(['name' => 'categoria']);
//        $this->objectProduct = (new \App\Controllers\Product());
//
//        $response = (new \App\Controllers\Product())->create([
//            'name' => 'opa',
//            'category_id' => 9876444,
//            'price' => 65.4,
//            'quantity' => 10
//        ]);

        $this->assertFalse(false);
    }


}